const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
const GET_GENRES = 'GET_GENRES';
const FILTERED_VIDEOGAMES = 'FILTERED_VIDEOGAMES';
const FILTER_CURRENT_VIDEOGAMES = 'FILTER_CURRENT_VIDEOGAMES';
const ORDER_VIDEOGAMES = 'ORDER_VIDEOGAAMES';
const GET_VIDEOGAME_BY_NAME = 'GET_VIDEOGAME_BY_NAME';
const GET_VIDEOGAME_BY_ID = 'GET_VIDEOGAME_BY_ID';
const CLEAR_VIDEOGAME_DETAIL = 'CLEAR_VIDEOGAME_DETAIL';

export {
    GET_VIDEOGAMES, 
    GET_GENRES, 
    FILTERED_VIDEOGAMES,
    FILTER_CURRENT_VIDEOGAMES,
    ORDER_VIDEOGAMES,
    GET_VIDEOGAME_BY_NAME,
    GET_VIDEOGAME_BY_ID,
    CLEAR_VIDEOGAME_DETAIL
};